### ISSUE TITLE
This is an error when I open vscode in extensionHost mode.

### ISSUE THREAD

**Issue by fallenleavesguy** [pvantrepote/tstools#4] opened 2016-07-29 11:55 UTC
This is an error when I open vscode in extensionHost mode, just didn't open any path.
<img width="659" alt="screen shot 2016-07-29 at 7 53 01 pm" src="https://cloud.githubusercontent.com/assets/9261562/17247524/63cbc548-55c6-11e6-9793-b5d05b820a4b.png">

**Comment by pvantrepote** [comment] 2016-07-29 12:11
Thanks for reporting this issue. 
I will look into it as soon as possible.

**Comment by pvantrepote** [comment] 2016-07-29 20:43
Do you have the stack trace by chance, can't reproduce it :(

**Comment by fallenleavesguy** [comment] 2016-07-30 04:56
you can fork or clone this minimal demo. https://github.com/yeluoqiuzhi/tstool-error-demo

**Comment by fallenleavesguy** [comment] 2016-07-30 04:58
I used vscode-insider 1.4.0 and latest tstools

**Comment by pvantrepote** [comment] 2016-07-30 10:57
Fixed in version 1.1.3

**Closed as completed by pvantrepote** 2016-07-30 10:57 UTC
